### ISSUE TITLE
No whitepaper?

### ISSUE THREAD

**Issue by tmaier** [contractvm/contractvm.github.io#1]
I just accessed http://contractvm.github.io/ and tried to open the Whitepaper linked there.
--> 404

**Comment by dakk** [comment]
Hi tmaier, we are rewriting the paper, I'll notice you when it's available; the old one is here: https://github.com/contractvm/contractvm.github.io/blob/master/cvm-white2.pdf

**Comment by dakk** [comment]
Resolved with 4ac4798
